@host=http://localhost:3000

# @name get_users
# @prompt userId
GET {{host}}/users/{{userId}} HTTP/1
###

# @name get_user_urls
# @prompt userId
GET {{host}}/users/{{userId}}/urls HTTP/1
###

# @name redirect_url
# @prompt urlId
GET {{host}}/urls/{{urlId}} HTTP/1
###