@host=http://localhost:3000

# @name get_me
# @prompt userId
GET {{host}}/me HTTP/1
user-id: {{userId}}
###

# @name patch_me
# @prompt userId
# @prompt name
# @prompt email
PATCH {{host}}/me HTTP/1
user-id: {{userId}}
content-type: application/json

{
    "name": "{{name}}",
    "email": "{{email}}"
}
###

# @name get_user_urls
# @prompt userId
GET {{host}}/urls HTTP/1
userId: {{userId}}
###

# @name redirect_url
# @prompt urlId
GET {{host}}/urls/{{urlId}} HTTP/1
###

# @name create_url
# @prompt destination
# @prompt userId
POST {{host}}/urls HTTP/1
content-type: application/json

{
   "destination": "{{destination}}",
   "userId": "{{userId}}"
}
###

# @name delete_url
# @prompt urlId
DELETE {{host}}/urls/{{urlId}} HTTP/1
###